
version: "3.5"

# External network
networks:
    ${CADDY_NETWORK_NAME}:
        external: true

volumes:
    postgres_data:


services:

    # Django app
    django:
        restart: always
        build:
            context: ${ROOT_FOLDER}/api
            dockerfile: ${ROOT_FOLDER}/api/Dockerfile
        expose:
            - 8000
        environment:
            - url=${API_URL}
        command:
            "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        env_file:
            - ${ROOT_FOLDER}/env/.env.${ENVIRONMENT}
        depends_on:
            - db
        networks:
            - ${CADDY_NETWORK_NAME}


    # Django database
    db:
        restart: always
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ${ROOT_FOLDER}/env/.env.db
        networks:
            - ${CADDY_NETWORK_NAME}
