# Generated by Django 3.0.7 on 2020-06-09 12:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiosonde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmo_id', models.CharField(max_length=50)),
                ('sonde_validtime', models.DateTimeField(null=True, verbose_name='sonde validtime')),
                ('station_name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=9)),
                ('temperatureK', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=None)),
                ('dewpointK', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=None)),
                ('pressurehPA', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('u_windMS', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=None)),
                ('v_windMS', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stn_wmoid', models.CharField(max_length=50)),
                ('stn_name', models.CharField(max_length=50)),
                ('stn_lat', models.DecimalField(decimal_places=4, max_digits=9)),
                ('stn_lon', models.DecimalField(decimal_places=4, max_digits=9)),
                ('stn_altitude', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
